# Generated by Django 4.2.4 on 2023-08-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sales_contact',
            new_name='sales_contact_id',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='sales_contact',
            new_name='sales_contact_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='client_contact',
            new_name='client_contact_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='client',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='contract',
            new_name='contract_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='support_contact',
            new_name='support_contact_id',
        ),
    ]
